console.log("To setup the database:")
console.log("1. Go to your Supabase project")
console.log("2. Open the SQL Editor")
console.log("3. Copy and paste the contents of scripts/001_create_tables.sql and run it")
console.log("4. Copy and paste the contents of scripts/002_insert_demo_data.sql and run it")
console.log("\nOr use Supabase CLI: npx supabase db push")
